'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('ru-RU').format(n)+' ₽';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const read=(k,d)=>{try{return JSON.parse(localStorage.getItem('dve:'+k))??d}catch{return d}};
const save=(k,v)=>{try{localStorage.setItem('dve:'+k,JSON.stringify(v))}catch{}};
let cart=read('cart',[]).filter(x=>PRODUCTS.some(p=>p.id===x.id)).map(x=>({...x,qty:Math.max(1,Math.min(99,Number(x.qty)||1))}));
let favorites=read('favorites',[]).filter(id=>PRODUCTS.some(p=>p.id===id));
let category='Все',mode='catalog',inquiry='',quiz={},quizStep=0;
const modal=$('#modal'), content=$('#modalContent');
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('visible'),2700)}
function open(html){content.innerHTML=html;if(!modal.open)modal.showModal()}
function updateCounts(){save('cart',cart);save('favorites',favorites);$('#cartCount').textContent=cart.reduce((s,x)=>s+x.qty,0);$('#favCount').textContent=favorites.length}
const heartIcon=filled=>'<svg viewBox="0 0 24 24" aria-hidden="true"'+(filled?' class="filled"':'')+'><path d="M20.8 4.7a5.5 5.5 0 0 0-7.8 0L12 5.8l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8l1.1 1.1L12 21l7.8-7.4 1.1-1.1a5.5 5.5 0 0 0-.1-7.8Z"/></svg>';
function art(p){return p.image?'<img src="'+esc(p.image)+'" alt="'+esc(p.name)+'" loading="lazy">':'<div class="product-placeholder"><span>Место для фото</span><small>'+esc(p.category)+'</small></div>'}
function renderCatalog(){
 $('#categories').innerHTML=CATEGORIES.map(c=>'<button data-category="'+esc(c)+'" class="'+(category===c&&mode==='catalog'?'active':'')+'" aria-pressed="'+(category===c&&mode==='catalog')+'">'+esc(c)+'</button>').join('');
 const q=$('#search').value.toLocaleLowerCase('ru'),min=$('#minPrice').value,max=$('#maxPrice').value;
 let list=PRODUCTS.filter(p=>(mode==='favorites'?favorites.includes(p.id):mode==='autumn'?p.autumn:category==='Все'||p.category===category)&&(!q||(p.name+' '+p.description+' '+p.category+' '+p.composition).toLocaleLowerCase('ru').includes(q))&&(!min||(p.price!==null&&p.price>=Number(min)))&&(!max||(p.price!==null&&p.price<=Number(max))));
 list.sort((a,b)=>$('#sort').value==='asc'?(a.price??Infinity)-(b.price??Infinity):$('#sort').value==='desc'?(b.price??-1)-(a.price??-1):Number(!!b.hit)-Number(!!a.hit));
 $('#products').innerHTML=list.length?list.map(p=>'<article class="product-card"><div class="product-photo"><button data-product="'+p.id+'" aria-label="Подробнее: '+esc(p.name)+'">'+art(p)+'</button>'+(p.soon?'<span class="badge">СКОРО</span>':p.hit?'<span class="badge">ХИТ</span>':p.preorder?'<span class="badge">ПОД ЗАКАЗ</span>':'')+'<button class="heart '+(favorites.includes(p.id)?'active':'')+'" data-favorite="'+p.id+'" aria-label="'+(favorites.includes(p.id)?'Убрать из избранного':'Добавить в избранное')+'" aria-pressed="'+favorites.includes(p.id)+'">'+heartIcon(favorites.includes(p.id))+'</button></div><div class="product-info"><h3><button data-product="'+p.id+'" style="font:inherit;text-align:left;padding:0">'+esc(p.name)+'</button></h3><button class="product-more" data-product="'+p.id+'">Подробнее о товаре</button><p class="stock">'+(p.stock===null?'Наличие уточняется':'Осталось '+p.stock+' шт.')+'</p><div class="product-bottom"><strong>'+(p.price!==null?money(p.price):'Цена')+'</strong><button class="button outline" data-add="'+p.id+'">В корзину ↗</button></div></div></article>').join(''):'<div class="empty"><h3>'+(category==='Новогодние композиции'?'Скоро появится':mode==='favorites'?'Здесь будут любимые букеты':'Подберём цветы специально для вас')+'</h3><p>'+(mode==='favorites'?'Добавьте понравившийся товар в избранное.':'Готовые варианты этой категории ещё не добавлены. Расскажите флористу о ваших пожеланиях.')+'</p><button class="button outline" data-action="'+(mode==='favorites'?'all':'contact')+'">'+(mode==='favorites'?'Вернуться в каталог':'Консультация флориста')+' ↗</button></div>';
}
function renderExtras(selected='Все'){const categories=['Все',...EXTRA_PRODUCTS.map(p=>p.category)];$('#extraCategories').innerHTML=categories.map(c=>'<button data-extra-category="'+esc(c)+'" class="'+(c===selected?'active':'')+'">'+esc(c)+'</button>').join('');const items=EXTRA_PRODUCTS.filter(p=>selected==='Все'||p.category===selected);$('#extraProducts').innerHTML=items.map(p=>'<article class="product-card"><div class="product-photo"><img src="'+esc(p.image)+'" alt="'+esc(p.category)+'" loading="lazy">'+(p.soon?'<span class="badge">СЕЗОННО</span>':'')+'</div><div class="product-info"><h3>'+p.name+'</h3><button class="product-more" data-inquiry="Дополнительный товар: '+esc(p.category)+'">Подробнее о товаре</button><p class="stock">'+(p.stock===null?'Наличие уточняется':'Осталось '+p.stock+' шт.')+'</p><div class="product-bottom"><strong>Цена</strong><button class="button outline" data-inquiry="Добавить: '+esc(p.category)+'">В корзину ↗</button></div></div></article>').join('')}

function showCategory(c,newMode='catalog'){category=c;mode=newMode;$('#search').value='';$('#minPrice').value='';$('#maxPrice').value='';renderCatalog();modal.close();$('#catalog').scrollIntoView({behavior:'smooth'})}
function add(id){let row=cart.find(x=>x.id===id);if(row){row.qty=Math.min(99,row.qty+1)}else cart.push({id,qty:1,selected:true});updateCounts();toast('Добавлено в корзину')}
function showProduct(id){const p=PRODUCTS.find(x=>x.id===id);open('<span class="eyebrow">'+esc(p.category)+'</span><h2>'+esc(p.name)+'</h2>'+(p.image?'<img class="product-detail-image" src="'+esc(p.image)+'" alt="'+esc(p.name)+'">':art(p))+'<p>'+esc(p.description)+'</p><p>Состав: '+esc(p.composition)+'</p><p>'+(p.stock===null?'Наличие уточнит флорист.':p.stock+' шт. в наличии')+'</p><h3>'+(p.price!==null?money(p.price):'Стоимость по согласованию')+'</h3><div class="actions"><button class="button" data-add="'+id+'">В корзину</button><button class="button outline" data-inquiry="'+esc(p.name)+'">Уточнить детали</button></div>')}
function totals(){let selected=cart.filter(x=>x.selected);return {selected,subtotal:selected.reduce((s,x)=>s+(PRODUCTS.find(p=>p.id===x.id).price||0)*x.qty,0),needsQuote:selected.some(x=>{let p=PRODUCTS.find(p=>p.id===x.id);return p.price===null||p.preorder||p.stock===null})}}
function showCart(){const t=totals();open('<h2>Ваша корзина</h2>'+(cart.length?cart.map(x=>{const p=PRODUCTS.find(p=>p.id===x.id);return '<article class="cart-item"><input type="checkbox" data-select="'+p.id+'" aria-label="Выбрать '+esc(p.name)+' для заказа" '+(x.selected?'checked':'')+'>'+(p.image?'<img src="'+esc(p.image)+'" alt="">':'<span class="cart-placeholder">Фото</span>')+'<div><h3>'+esc(p.name)+'</h3><p>'+(p.price===null?'Цена по согласованию':money(p.price*x.qty))+'</p><button class="remove" data-remove="'+p.id+'">Убрать</button></div><div class="qty"><button data-qty="'+p.id+'" data-delta="-1" aria-label="Уменьшить количество">−</button><span>'+x.qty+'</span><button data-qty="'+p.id+'" data-delta="1" aria-label="Увеличить количество">+</button></div></article>'}).join('')+'<p class="notice">Отметьте товары, которые хотите заказать сейчас. Букет – живая работа: оттенки цветов и упаковка могут немного отличаться от фото. Все существенные замены согласуем с вами.</p><button class="text-button" data-action="extras">Добавить вазу, открытку или подарок ↗</button><div class="cart-total"><span>Выбранные товары</span><strong>'+(t.subtotal?money(t.subtotal):'По согласованию')+'</strong></div><p class="catalog-note">Доставка рассчитывается отдельно. Товары без указанной цены флорист рассчитает перед оплатой.</p><button class="button" data-action="checkout" '+(!t.selected.length?'disabled':'')+'>Оформить выбранное ↗</button>':'<p>Пока здесь нет цветов. Самое время выбрать что-нибудь красивое.</p><button class="button" data-action="all">Перейти в каталог ↗</button>'))}
const consent='<label class="checkbox"><input type="checkbox" name="consent" required><span>Согласен(на) на обработку имени, телефона и данных заявки для обратной связи и оформления заказа. <button type="button" class="text-button" data-legal="privacy">Подробнее</button></span></label>';
function contact(subject=''){inquiry=subject;open('<span class="eyebrow">ДАВАЙТЕ СОБЕРЁМ ВАШУ ИСТОРИЮ</span><h2>Консультация флориста</h2><p>Оставьте имя, телефон и пожелания. Можно отправить подготовленное сообщение в WhatsApp или позвонить нам.</p><form class="form" id="contactForm"><label>Как к вам обращаться<input name="name" autocomplete="given-name" required maxlength="80"></label><label>Ваш телефон<input name="phone" type="tel" autocomplete="tel" required placeholder="+7 (___) ___-__-__" pattern="[+0-9 ()-]{10,20}"></label><label>Ваш вопрос<textarea name="message" required maxlength="3000">'+esc(subject)+'</textarea></label>'+consent+'<button class="button" type="submit">Подготовить сообщение ↗</button><a class="button outline" href="tel:'+SITE.phone+'">Позвонить</a><p id="formStatus" role="status"></p></form>')}
function handoff(text){open('<h2>Сообщение готово</h2><p>Откройте WhatsApp и отправьте сообщение флористу. Пока вы не нажмёте «Отправить» в мессенджере, магазин не получит заявку.</p><a class="button" target="_blank" rel="noopener" href="https://wa.me/79507302788?text='+encodeURIComponent(text)+'">Открыть WhatsApp ↗</a><p>Или позвоните: <a href="tel:'+SITE.phone+'">'+SITE.phoneDisplay+'</a></p><details><summary>Посмотреть текст сообщения</summary><p style="white-space:pre-wrap">'+esc(text)+'</p></details>')}
function checkout(){const t=totals();if(!t.selected.length)return;open('<h2>Оформление заказа</h2><form id="checkoutForm" class="form"><div class="form-grid"><label>Ваше имя<input name="name" required autocomplete="given-name" maxlength="80"></label><label>Телефон заказчика<input name="phone" type="tel" required autocomplete="tel" placeholder="+7 (___) ___-__-__" pattern="[+0-9 ()-]{10,20}"></label></div><label>Получение<select name="delivery" id="delivery"><option value="courier">Доставка</option><option value="pickup">Самовывоз с Чичерина, 5В</option></select></label><div id="deliveryFields"><label>Адрес доставки<input name="address" id="deliveryAddress" autocomplete="street-address" placeholder="Челябинск, улица, дом, квартира" required maxlength="250"></label><label>Район доставки<select name="district" id="district"><option value="unknown">Определить с менеджером</option><option value="400">Северо-запад / Парковый – 400 ₽</option><option value="450">Центр / ЧТЗ – 450 ₽</option><option value="500">ЧМЗ / АМЗ / Ленинский – 500 ₽</option><option value="remote">Чурилово-Шагол / Кременкуль / другой – по договорённости</option></select></label><small>Укажите район для предварительного расчёта. Точную зону по адресу подтвердит менеджер.</small></div><div class="form-grid"><label>Дата<input type="date" name="date" id="orderDate" required></label><label>Время<select name="time" required><option>9:00–11:00</option><option>11:00–13:00</option><option>13:00–15:00</option><option>15:00–17:00</option><option>17:00–20:00</option></select></label></div><label>Пожелания и текст открытки<textarea name="message" maxlength="3000"></textarea></label><section id="bonusStatus" class="notice loyalty" data-posiflora-status="unavailable"><strong>Бонусная программа</strong><p>После подключения Posiflora здесь безопасно появятся баланс, максимум к списанию и ожидаемое начисление. Проверка телефона будет выполняться только через backend.</p><div data-loyalty-redeem hidden><label class="checkbox"><input type="checkbox" name="useBonus"><span>Использовать бонусы</span></label><label>Сколько бонусов списать?<input type="number" name="bonusAmount" min="0"><button type="button" class="text-button" data-action="maxBonus">Списать максимум</button></label></div><small>После покупки вам будут начислены бонусы по программе лояльности.</small></section><div id="orderSummary"></div>'+consent+'<button class="button" type="submit">Отправить заявку через WhatsApp ↗</button><button class="button outline" type="button" disabled>Онлайн-оплата пока недоступна</button><small>Сейчас заказ и оплата согласуются с менеджером. Выбранные товары сохранятся в корзине.</small></form>');const today=new Date();$('#orderDate').min=new Date(today.getTime()-today.getTimezoneOffset()*60000).toISOString().slice(0,10);$('#orderDate').value=$('#orderDate').min;updateOrder()}
function updateOrder(){const t=totals(),pickup=$('#delivery').value==='pickup',d=$('#district').value,fee=pickup?0:/^\d+$/.test(d)?Number(d):null;$('#deliveryFields').hidden=pickup;$('#deliveryAddress').required=!pickup;$('#orderSummary').innerHTML='<div class="cart-total"><span>Товары с указанной ценой</span><strong>'+money(t.subtotal)+'</strong></div><p>Доставка: '+(fee===null?'по согласованию':fee===0?'бесплатно':money(fee))+'</p><div class="cart-total"><span>Предварительно</span><strong>'+money(t.subtotal+(fee||0))+'</strong></div>'+(t.needsQuote||fee===null?'<p class="notice">Флорист подтвердит наличие, окончательную стоимость и условия доставки перед оплатой.</p>':'')}
const quizQuestions=[['На какую сумму ориентируемся?',['До 1 500 ₽','До 2 000 ₽','До 2 500 ₽','До 3 000 ₽','Другой бюджет']],['Каким будет ваш подарок?',['Нежным','Ярким','Романтичным','Спокойным']],['Как оформим букет?',['Упаковка','Лента','Корзиночка']]];
function showQuiz(){if(quizStep>=quizQuestions.length){contact('Подбор букета:\nБюджет: '+quiz[0]+'\nНастроение: '+quiz[1]+'\nОформление: '+quiz[2]+'\nЛюбимые цветы и что не добавлять: ');return}const [q,opts]=quizQuestions[quizStep];open('<div class="quiz-step">ШАГ '+(quizStep+1)+' ИЗ 3</div><h2>'+q+'</h2><div class="quiz-options">'+opts.map(o=>'<button data-quiz="'+esc(o)+'">'+o+'</button>').join('')+'</div>'+(quizStep?'<button class="text-button" data-action="quizBack">← Назад</button>':''))}
function renderReviews(){$('#reviewList').innerHTML=REVIEWS.map((r,i)=>'<article class="review"><div class="review-head"><h3>'+r.name+'</h3><span aria-label="5 звёзд">★★★★★</span></div><p>'+esc(r.text)+'</p><button class="review-photo" data-review="'+i+'" aria-label="Открыть фото к отзыву '+r.name+'"><img src="'+esc(r.image)+'" alt="Букет на фотографии к отзыву '+r.name+'" loading="lazy"></button></article>').join('')}
function nextHoliday(month,day){const n=new Date(),y=n.getFullYear();let d=new Date(y,month-1,day,23,59,59);if(d<n)d=new Date(y+1,month-1,day,23,59,59);return d}
function renderHolidays(){let dates=[['День учителя',10,5],['Новый год',1,1],['14 февраля',2,14],['8 Марта',3,8],['Выпускной',6,25],['1 сентября',9,1]].map(([name,m,d])=>({name,date:nextHoliday(m,d)}));let n=new Date(),y=n.getFullYear(),md=new Date(y,11,0);md.setDate(md.getDate()-md.getDay());if(md<n){md=new Date(y+1,11,0);md.setDate(md.getDate()-md.getDay())}dates.push({name:'День матери',date:md});dates.sort((a,b)=>a.date-b.date);$('#holidayList').innerHTML=dates.map(x=>'<article class="holiday"><span>'+x.date.toLocaleDateString('ru-RU',{day:'numeric',month:'long'})+(x.name==='Выпускной'?' · дату уточним':'')+'</span><h3>'+x.name+'</h3><div class="countdown">'+Math.max(0,Math.ceil((x.date-new Date())/86400000))+' <small>дней до повода</small></div><button class="text-button" data-inquiry="Предзаказ: '+x.name+'">Заказать заранее ↗</button></article>').join('')}
function legal(type){const texts={privacy:['Обработка данных','Для ответа на обращение и согласования заказа магазин использует имя, телефон, адрес доставки и текст пожеланий, которые вы передаёте добровольно. При отправке через WhatsApp данные передаются в выбранный вами мессенджер. На этой версии сайта данные формы не отправляются автоматически. Для вопросов об обработке или удаления переданных данных: popis191293@mail.ru, +7 (950) 730-27-88. Контактный адрес: Челябинск, Чичерина, 5В. ИНН 741855975971.'],terms:['Условия заказа','Фотографии показывают примеры работ. Наличие цветов, окончательный состав, упаковку, цену и время доставки подтверждает флорист. Доставка: Северо-запад и Парковый – 400 ₽; Центр и ЧТЗ – 450 ₽; ЧМЗ, АМЗ и Ленинский – 500 ₽; удалённые районы – по договорённости. Экзотические растения привозятся под заказ ориентировочно за неделю. Онлайн-оплата в текущей версии не подключена. Все условия согласуются до оплаты.'],cookies:['Хранение настроек','Корзина, избранное и отметка об ознакомлении сохраняются только в локальном хранилище вашего браузера. Внешняя Google Карта может использовать собственные cookies. Вы можете удалить данные сайта в настройках браузера.']};const [h,p]=texts[type];open('<h2>'+h+'</h2><p>'+p+'</p>')}
document.addEventListener('click',e=>{
 const b=e.target.closest('button,a');if(!b)return;
 if(b.hasAttribute('data-close')){b.closest('dialog').close();return}
 if(b.dataset.extraCategory){renderExtras(b.dataset.extraCategory);return}
 if(b.dataset.category){e.preventDefault();showCategory(b.dataset.category);return}
 if(b.dataset.add){add(b.dataset.add);return}
 if(b.dataset.product){showProduct(b.dataset.product);return}
 if(b.dataset.favorite){let id=b.dataset.favorite;favorites=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];updateCounts();renderCatalog();return}
 if(b.dataset.remove){cart=cart.filter(x=>x.id!==b.dataset.remove);updateCounts();showCart();return}
 if(b.dataset.qty){const x=cart.find(x=>x.id===b.dataset.qty);x.qty=Math.max(1,Math.min(99,x.qty+Number(b.dataset.delta)));updateCounts();showCart();return}
 if(b.dataset.inquiry!==undefined){contact(b.dataset.inquiry);return}
 if(b.dataset.review!==undefined){let r=REVIEWS[Number(b.dataset.review)];open('<h2>Фото к отзыву '+r.name+'</h2><img class="lightbox-image" src="'+esc(r.image)+'" alt="Фото букета из отзыва '+r.name+'">');return}
 if(b.dataset.quiz){quiz[quizStep]=b.dataset.quiz;quizStep++;showQuiz();return}
 if(b.dataset.legal){legal(b.dataset.legal);return}
 switch(b.dataset.action){case'cart':showCart();break;case'favorites':showCategory('Все','favorites');break;case'autumn':showCategory('Все','autumn');break;case'all':showCategory('Все');break;case'checkout':checkout();break;case'contact':contact();break;case'quiz':quiz={};quizStep=0;showQuiz();break;case'quizBack':quizStep--;showQuiz();break;case'extras':modal.close();$('#extras').scrollIntoView({behavior:'smooth'});break}
});
document.addEventListener('change',e=>{if(e.target.dataset.select){cart.find(x=>x.id===e.target.dataset.select).selected=e.target.checked;updateCounts();showCart()}if(['delivery','district'].includes(e.target.id))updateOrder()});
document.addEventListener('submit',e=>{
 if(!['contactForm','checkoutForm'].includes(e.target.id))return;e.preventDefault();const data=Object.fromEntries(new FormData(e.target));
 if(data.phone.replace(/\D/g,'').length<10){toast('Проверьте номер телефона');return}
 if(e.target.id==='contactForm'){handoff('Вопрос с сайта «Две в Цвете»\nИмя: '+data.name+'\nТелефон: '+data.phone+'\n'+data.message);return}
 const t=totals();let district=$('#district').selectedOptions[0].textContent;
 handoff('Заказ с сайта «Две в Цвете»\n'+t.selected.map(x=>{let p=PRODUCTS.find(p=>p.id===x.id);return p.name+' × '+x.qty+' – '+(p.price===null?'стоимость уточнить':money(p.price*x.qty))}).join('\n')+'\nИмя: '+data.name+'\nТелефон: '+data.phone+'\n'+(data.delivery==='pickup'?'Самовывоз с Чичерина, 5В':'Доставка: '+data.address+'\nРайон: '+district)+'\nДата: '+data.date+'\nВремя: '+data.time+'\nПожелания: '+data.message+'\nПрошу подтвердить наличие и итоговую стоимость.');
});
$('#search').addEventListener('input',()=>{mode='catalog';renderCatalog()});['minPrice','maxPrice'].forEach(id=>$('#'+id).addEventListener('input',renderCatalog));$('#sort').addEventListener('change',renderCatalog);
const menu=$('#menuDialog');$('.menu-trigger').addEventListener('click',()=>{menu.showModal();$('.menu-trigger').setAttribute('aria-expanded','true')});menu.addEventListener('close',()=>$('.menu-trigger').setAttribute('aria-expanded','false'));$$('#menuDialog nav a').forEach(a=>a.addEventListener('click',()=>menu.close()));
$$('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}}));
$$('[data-map]').forEach(a=>a.href=SITE.mapsUrl);$('#storeMap').src=SITE.mapsEmbed;
$('#socialLinks').innerHTML=Object.entries(SITE.socials).filter(([,url])=>url).map(([k,url])=>'<a target="_blank" rel="noopener" href="'+esc(url)+'">'+({whatsapp:'WhatsApp',vk:'ВКонтакте',telegram:'Telegram',max:'MAX'}[k])+' ↗</a>').join('');
$('#year').textContent=new Date().getFullYear();updateCounts();renderCatalog();renderExtras();renderReviews();renderHolidays();
if(!read('cookies',false))$('#cookies').hidden=false;$('#acceptCookies').addEventListener('click',()=>{save('cookies',true);$('#cookies').hidden=true});
setTimeout(()=>{if(!read('bonusSeen',false)&&!modal.open&&!menu.open){save('bonusSeen',true);open('<span class="eyebrow">ПРИЯТНО ВОЗВРАЩАТЬСЯ</span><h2>Цветы радуют.<br>Бонусы остаются.</h2><p>Пять процентов от каждого заказа копится на бонусный счёт. Бонусами можно оплатить до 20% стоимости букета. Срока сгорания нет.</p><button class="button" data-action="all">Выбрать букет ↗</button><p class="catalog-note">Бонусами нельзя оплатить заказ 8 Марта, 14 февраля, в Новый год и День матери. Баланс и списание сейчас уточняйте у флориста.</p>')}},10000);
