const {chromium}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:4175');
await page.evaluate(()=>{localStorage.setItem('dve:bonusSeen','true');localStorage.setItem('dve:cookies','true')});
await page.reload();await page.waitForTimeout(700);
assert.equal(await page.locator('.review').count(),6);
assert.deepEqual(await page.locator('.review-photo img').evaluateAll(a=>a.map(i=>i.getAttribute('src'))),[1536,1537,1538,1539,1540,1541].map(n=>'https://storage.yandexcloud.net/dve-v-tsvete/%D0%A4%D0%BE%D1%82%D0%BE/IMG_'+n+'.jpeg'));
assert.equal(await page.locator('body').innerText().then(t=>t.includes('\u2014')),false);
await page.screenshot({path:'preview/desktop.png',fullPage:true});
await page.locator('[data-add="mixed"]').click();
await page.locator('[data-action="cart"]').click();
assert.equal(await page.locator('.cart-item').count(),1);
await page.locator('[data-action="checkout"]').click();
await page.locator('#district').selectOption('400');
assert.match(await page.locator('#orderSummary').innerText(),/400/);
await page.locator('#district').selectOption('remote');
assert.match(await page.locator('#orderSummary').innerText(),/по согласованию/);
await page.locator('#modal [data-close]').click();
await page.locator('[data-favorite="mixed"]').click();
await page.locator('[data-action="favorites"]').click();
assert.equal(await page.locator('.product-card').count(),1);
await page.locator('[data-category="Все"]').click();
await page.locator('#search').fill('СВАДЕБНЫЕ');
assert.equal(await page.locator('#products .product-card').count(),1);
await page.locator('#search').fill('');
await page.locator('[data-review="0"]').click();
assert.equal(await page.locator('.lightbox-image').getAttribute('src'),'https://storage.yandexcloud.net/dve-v-tsvete/%D0%A4%D0%BE%D1%82%D0%BE/IMG_1536.jpeg');
await page.locator('#modal [data-close]').click();
await page.setViewportSize({width:390,height:844});
await page.goto('http://127.0.0.1:4175');
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
await page.screenshot({path:'preview/mobile.png',fullPage:true});
await page.locator('.menu-trigger').click();assert.equal(await page.locator('#menuDialog').evaluate(d=>d.open),true);
await page.locator('#menuDialog a[href="#reviews"]').click();assert.equal(await page.locator('#menuDialog').evaluate(d=>d.open),false);
assert.deepEqual(errors,[]);
console.log('PASS: 6 review/photo mappings, en dashes, cart, delivery, favorites, search, lightbox, mobile width, menu, no JS errors');
await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
